language: python
python: "3.9"

install:
  - pip install pytest-pylint
  - pip install pytest-flake8
  - pip install pylint_flask_sqlalchemy
  - pip install -r requirements.txt

services:
  - docker

branches:
  only: 
    - master

jobs:
  include:
    - stage: test
      if: type = pull_request
      script: pytest --flake8 --pylint 
    - stage: build
      if: type = pull_request
      script: docker build . --file Dockerfile -t recio_rest_api
    - stage: deploy
      if: type = push
      script: pytest
      script: docker build . --file Dockerfile -t recio_rest_api
      script: docker run recio_rest_api
      script: docker ps -a
