language: python
python: "3.9"

install:
  - pip install pytest-pylint
  - pip install pytest-flake8
  - pip install -r requirements.txt

script:
  - pytest --flake8 --pylint

branches:
  only: 
    - master
