language: python
python: "3.9"

env:
  - DOCKER_COMPOSE_VERSION=1.28.5

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip install pytest-pylint
  - pip install pytest-flake8
  - pip install pylint_flask_sqlalchemy
  - pip install -r requirements.txt

services:
  - docker

branches:
  only: 
    - master

jobs:
  include:
    - stage: lint
      if: type = pull_request
      script: pytest --flake8 --pylint --ignore=tests 
    - stage: build
      if: type = pull_request
      script: docker-compose build
    - stage: test
      if: type = pull_request
      script: docker-compose up --build -d && sleep 60 && pytest tests

    - stage: build
      if: type = push
      script: docker-compose up -d
