version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'recio'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
  recio:
    build: ./
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - 5000:5000
    environment:
      - HOST=db
      - USER=user
      - PASSWORD=password
    expose:
      - 5000