version: "3.3"
services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - "80:8080"
    volumes:
      - ./docs/api.yaml:/api.yaml
    environment:
      SWAGGER_JSON: /api.yaml