name: deploy on push
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Deploying backend
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.RECIO_REMOTE_SSH }}
        script: cd /root/recio-backend && git pull && docker-compose up -d
